autoscrollduration = 10
brightness = 0
contrast = 1 
displayrotation = 0
exposure = 75
font = 'Typewriter.ttf'
fontsize = 16
photoflash = 'Yes'
showleds = 'Yes'
showsplashscreen = 'No'
timelapseduration = 1
timestampphoto= 'No'
whitebalance = 'auto'